	<div class="emoji">
				<img src="assets/emoji/1.png" class="emoji-same">
				<img src="assets/emoji/2.png" class="emoji-same">
				<img src="assets/emoji/3.png" class="emoji-same">
				<img src="assets/emoji/4.png" class="emoji-same">
				<img src="assets/emoji/5.png" class="emoji-same">
				<img src="assets/emoji/6.png" class="emoji-same">
				<img src="assets/emoji/7.png" class="emoji-same">
				<img src="assets/emoji/8.png" class="emoji-same">
				<img src="assets/emoji/9.png" class="emoji-same">
				<img src="assets/emoji/10.png" class="emoji-same">
				<img src="assets/emoji/11.png" class="emoji-same">
				<img src="assets/emoji/12.png" class="emoji-same">
				<img src="assets/emoji/13.png" class="emoji-same">
				<img src="assets/emoji/14.png" class="emoji-same">
				<img src="assets/emoji/15.png" class="emoji-same">
				<img src="assets/emoji/16.png" class="emoji-same">
				<img src="assets/emoji/17.png" class="emoji-same">
				<img src="assets/emoji/18.png" class="emoji-same">
				<img src="assets/emoji/19.png" class="emoji-same">
				<img src="assets/emoji/20.png" class="emoji-same">
				<img src="assets/emoji/21.png" class="emoji-same">
				<img src="assets/emoji/22.png" class="emoji-same">
				<img src="assets/emoji/23.png" class="emoji-same">
				<img src="assets/emoji/24.png" class="emoji-same">
				<img src="assets/emoji/25.png" class="emoji-same">
				<img src="assets/emoji/26.png" class="emoji-same">
				<img src="assets/emoji/27.png" class="emoji-same">
				<img src="assets/emoji/28.png" class="emoji-same">
			</div>